### ISSUE TITLE
jspm bundle (0.16.43) replaces angular directive require with $__require

### ISSUE THREAD

**Issue by nelisbijl** [jspm/jspm.io#53] opened 2016-08-24 08:16 UTC
Found in 0.16.43
Luckily I had another project not having this problem. That was using 0.16.41. Downgrading jspm resolved my problem (for now)

**Comment by guybedford** [comment] 2016-08-24 15:01
Thanks for posting, this seems like a duplicate of https://github.com/jspm/jspm-cli/issues/2046.

**Closed by guybedford** 2016-08-24 15:01 UTC
